### ISSUE TITLE
Add license

### ISSUE THREAD

**Issue by Perdex** [ravi4ram/Bell-Nozzle#1]
Hello!
Could you add a license; can this work be used by others?

I'm working at a space propulsion startup, and this could be a nice tool for showing our new employees some basics about rocket nozzles. I'd be very happy if you licensed this for example under MIT license so we could use this script!

(Basically, you can just copy-paste it from here https://choosealicense.com/licenses/mit/# )

**Comment by ravi4ram** [comment]
Hi,
Included the MIT license.  Happy to know that this project will be used.
