### ISSUE TITLE
Wrong multiplier for 60% nozzle

### ISSUE THREAD

**Issue by doctorx84** [ravi4ram/Bell-Nozzle#2]
On line 152, the multiplier should be 0.6 and not 0.8.

`if l_percent == 60:`
`     theta_n = theta_n_60; theta_e = theta_e_60;`
`     Ln = 0.8 * f1` <-- Issue
`elif l_percent == 80:`

Best regards

**Comment by ravi4ram** [comment]
Thanks for your inputs. Corrected the factor to 0.6
