### ISSUE TITLE
Returns in degree rather than radian

### ISSUE THREAD

**Issue by pasdeconneriescettefoisci** [ravi4ram/Bell-Nozzle#3]
https://github.com/ravi4ram/Bell-Nozzle/blob/1bc73d4ae3b9e149a264e74fc467480a8a2562b8/bell_nozzle.py#L167

Little mistake at line 167, the angles is returned in degree rather than radian.

Martin

**Comment by ravi4ram** [comment]
Thanks for making robust with extremum value testing. Fixed it.
