### ISSUE TITLE
Error running code due to positional arguments mismatch

### ISSUE THREAD

**Issue by calmymail** [ravi4ram/Bell-Nozzle#5]
Python 3.12.5 (tags/v3.12.5:ff3bc82, Aug  6 2024, 20:45:27) [MSC v.1940 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license()" for more information.

= RESTART: \Bell-Nozzle-master\bell_nozzle.py
Traceback (most recent call last):
  File "\Bell-Nozzle-master\bell_nozzle.py", line 437, in <module>
    plot(title, throat_radius, angles, contour)
  File "\Bell-Nozzle-master\bell_nozzle.py", line 413, in plot
    plot_nozzle(ax1, title, throat_radius, angles, contour)
  File "\Bell-Nozzle-master\bell_nozzle.py", line 290, in plot_nozzle
    draw_angle_arc(ax, theta_n, origin, degree_symbol )
  File "\Bell-Nozzle-master\bell_nozzle.py", line 342, in draw_angle_arc
    arc_obj = Arc([startx, starty], 1, 1, 0, 0, math.degrees(theta_n), color='k' )
TypeError: Arc.__init__() takes 4 positional arguments but 7 were given

**Comment by calmymail** [comment]
Issue resolved... Matplotlib updated the arc function.  Update line 343 to read:

	arc_obj = Arc([startx, starty], 1, 1, angle=0, theta1=0, theta2=math.degrees(theta_n), color='k' )

**Comment by ravi4ram** [comment]
Thanks for pointing that out.    
Mentioned the last tested version (matplotlib ver 2.1.1) on the main page. 
Updated with changes.
